apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teleport-plugin-request-autoreviewer.fullname" . }}
  labels:
    {{- include "teleport-plugin-request-autoreviewer.labels" . | nindent 4 }}
  {{- with (include "teleport-plugin-request-autoreviewer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teleport-plugin-request-autoreviewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "teleport-plugin-request-autoreviewer.podTemplateAnnotations" . | nindent 8 }}
      labels:
        {{- include "teleport-plugin-request-autoreviewer.podTemplateLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "teleport-plugin-request-autoreviewer.serviceAccountName" . }}
      securityContext:
        {{- include "teleport-plugin-request-autoreviewer.podSecurityContext" . | nindent 8 }}
      containers:
        - name: teleport-plugin-request-autoreviewer
          securityContext:
            {{- include "teleport-plugin-request-autoreviewer.securityContext" . | nindent 12 }}
          image: {{ include "teleport-plugin-request-autoreviewer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.healthPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if or .Values.teleport.identityFile .Values.tbot.enabled }}
            - name: identity
              mountPath: /etc/teleport/identity
              subPath: identity
              readOnly: true
            {{- end }}
            - name: tmp
              mountPath: /tmp
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "teleport-plugin-request-autoreviewer.fullname" . }}-config
        {{- if or .Values.teleport.identityFile .Values.tbot.enabled }}
        - name: identity
          secret:
            secretName: {{ include "teleport-plugin-request-autoreviewer.identitySecretName" . }}
            defaultMode: 0400
        {{- end }}
        - name: tmp
          emptyDir: {}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
