{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "teleport-plugin-request-autoreviewer.fullname" . }}
  labels:
    {{- include "teleport-plugin-request-autoreviewer.labels" . | nindent 4 }}
  {{- with (include "teleport-plugin-request-autoreviewer.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teleport-plugin-request-autoreviewer.selectorLabels" . | nindent 6 }}
{{- end }}
