apiVersion: v2
name: teleport-plugin-request-autoreviewer
description: A Helm chart for Teleport Auto-reviewer service that automatically reviews and rejects access requests based on configurable rules, with optional tbot integration for automated identity management
type: application
version: 0.2.0
appVersion: "1.0.0"
home: https://github.com/your-org/teleport-plugin-request-autoreviewer
sources:
  - https://github.com/your-org/teleport-plugin-request-autoreviewer
maintainers:
  - name: Santiago Espinosa Mooser
    email: contact@santiago-mooser.com
keywords:
  - teleport
  - access-control
  - security
  - automation
  - tbot
  - machine-id
annotations:
  # Security best practices
  seccomp.security.alpha.kubernetes.io/pod: runtime/default
  container.apparmor.security.beta.kubernetes.io/teleport-plugin-request-autoreviewer: runtime/default
  container.apparmor.security.beta.kubernetes.io/tbot: runtime/default
